name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --release
  
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mouse_speed_profiler-${{ github.sha }}
        path: |
          target/release/mouse_speed_profiler.exe
        if-no-files-found: error
  
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          target/release/mouse_speed_profiler.exe
